xcopy /r /k /d M:\chess\xboard\backend.c .
xcopy /r /k /d M:\chess\xboard\backend.h .
xcopy /r /k /d M:\chess\xboard\backendz.h .
xcopy /r /k /d M:\chess\xboard\ChangeLog .
xcopy /r /k /d M:\chess\xboard\alpha\comment.awk .
xcopy /r /k /d M:\chess\xboard\common.h .
xcopy /r /k /d M:\chess\xboard\COPYING .
xcopy /r /k /d M:\chess\xboard\COPYRIGHT .
xcopy /r /k /d M:\chess\xboard\FAQ.html .
xcopy /r /k /d M:\chess\xboard\alpha\FAQ .
xcopy /r /k /d M:\chess\xboard\frontend.h .
xcopy /r /k /d M:\chess\xboard\gamelist.c .
xcopy /r /k /d M:\chess\xboard\ics-addresses .
xcopy /r /k /d M:\chess\xboard\ics-info .
xcopy /r /k /d M:\chess\xboard\kk13.pgn .
xcopy /r /k /d M:\chess\xboard\lists.c .
xcopy /r /k /d M:\chess\xboard\lists.h .
xcopy /r /k /d M:\chess\xboard\moves.c .
xcopy /r /k /d M:\chess\xboard\moves.h .
xcopy /r /k /d M:\chess\xboard\parser.l .
REM xcopy /r /k /d M:\chess\xboard\alpha\parser.c .
xcopy /r /k /d M:\chess\xboard\pgntags.c .
xcopy /r /k /d M:\chess\xboard\ToDo .
xcopy /r /k /d M:\chess\xboard\zippy.c .
xcopy /r /k /d M:\chess\xboard\zippy.h .
xcopy /r /k /d M:\chess\xboard\zippy.README .
xcopy /r /k /d M:\chess\xboard\engine-intf.html .
xcopy /r /k /d M:\chess\xboard\ics-parsing.txt .
xcopy /r /k /d M:\chess\xboard\borland.txt .
xcopy /r /k /d M:\chess\xboard\cygwin.txt .
